# This is a basic workflow to help you get started with Actions
- name: Upload_TO_VM
      uses: appleboy/scp-action@master
      with: 
            host: ${{ secrets.AZ_MACHINE_IP }}        
            username: ${{ secrets.AZ_USER_NAME }}  
            password: ${{ secrets.AZ_PASSWORD }}
            port: 22
            source: SpringBootHelloWorldExample.war      
            target: ~/
    
- name: Deploy_application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZ_MACHINE_IP }}        
        username: ${{ secrets.AZ_USER_NAME }}  
        password: ${{ secrets.AZ_PASSWORD }}
        port: 22
        script: whoami | mkdir /home/sample/sample.txt
